`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module Name: top_monitored_auto
// Description: AUTO-GENERATED Top-Level Instrumented Wrapper
//              Generated by scripts/instrument_sensors.py
//              Tapped Rare Signal Nets: TEST_PATTERN, enable
// IEEE 1364-2001 Verilog Standard Compliant
//////////////////////////////////////////////////////////////////////////////////

module top_monitored_auto (
    input  wire        clk,
    input  wire        rst,
    input  wire        enable,
    input  wire        test_mode,
    input  wire [31:0] data_in,
    input  wire [31:0] key_in,
    output wire [31:0] data_out,
    output wire        corner_case_flag,
    output wire [15:0] ro1_freq,
    output wire [15:0] ro2_freq,
    output wire [15:0] freq_delta
);

    // Primary Datapath Instance
    top datapath_core (
        .clk(clk),
        .rst(rst),
        .enable(enable),
        .test_mode(test_mode),
        .data_in(data_in),
        .key_in(key_in),
        .data_out(data_out),
        .corner_case_flag(corner_case_flag)
    );

    // Sensor 1: Baseline Reference Sensor
    ring_oscillator ro_sensor_baseline (
        .enable(enable),
        .rare_net_in(1'b0),
        .ro_out(),
        .freq_count(ro1_freq)
    );

    // Sensor 2: Auto-Tapped Rare Net Sensor (Tapped Signal: TEST_PATTERN)
    ring_oscillator ro_sensor_tapped (
        .enable(enable),
        .rare_net_in(TEST_PATTERN),
        .ro_out(),
        .freq_count(ro2_freq)
    );

    // Differential Frequency Delta Calculation (|RO1 - RO2|)
    assign freq_delta = (ro1_freq >= ro2_freq) ? (ro1_freq - ro2_freq) : (ro2_freq - ro1_freq);

endmodule
