#!/usr/bin/env python3
"""
==================================================================================
Script: instrument_sensors.py
Description: Automated Ring Oscillator Sensor Instrumentation Tool.
             Parses pre-silicon rare net profile and automatically generates an
             instrumented top-level Verilog wrapper (top_monitored_auto.v)
             tapping 5-stage RO sensors onto the top N dormant rare signal nets.
IEEE 1364-2001 Compliant EDA Auto-Instrumentation Engine
==================================================================================
"""

import argparse
import json
import re
import sys
from pathlib import Path


def parse_rare_profile(profile_path: Path, top_n: int):
    """
    Parse JSON rare net profile and extract top N most dormant rare nets.
    """
    if not profile_path.exists():
        print(f"[!] Warning: Profile '{profile_path}' not found. Using default rare net 'corner_case_flag'.", file=sys.stderr)
        return ["corner_case_flag"]

    with open(profile_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    rare_nets = data.get("rare_nets", [])
    # Sort rare nets by switching probability ascending (most dormant first)
    sorted_rare = sorted(rare_nets, key=lambda x: x.get("switching_prob", 1.0))

    tapped_nets = []
    for r in sorted_rare:
        raw_name = r.get("net_name", "")
        # Extract signal leaf name (e.g., "tb_top.uut.corner_case_flag" -> "corner_case_flag")
        leaf_name = raw_name.split(".")[-1]
        # Remove bit slice bracket if present (e.g. "data_out[0]" -> "data_out")
        leaf_name = re.sub(r"\[.*\]", "", leaf_name)

        if leaf_name and leaf_name not in tapped_nets and leaf_name != "clk" and leaf_name != "rst":
            tapped_nets.append(leaf_name)
        if len(tapped_nets) >= top_n:
            break

    if not tapped_nets:
        tapped_nets = ["corner_case_flag"]

    return tapped_nets


def generate_auto_monitored_verilog(verilog_path: Path, tapped_nets: list, output_path: Path):
    """
    Generate auto-instrumented Verilog wrapper instantiating top core and dual/multi RO sensors.
    """
    sensor_taps_comment = ", ".join(tapped_nets)
    target_tap = tapped_nets[0] if tapped_nets else "corner_case_flag"

    verilog_code = f"""`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module Name: top_monitored_auto
// Description: AUTO-GENERATED Top-Level Instrumented Wrapper
//              Generated by scripts/instrument_sensors.py
//              Tapped Rare Signal Nets: {sensor_taps_comment}
// IEEE 1364-2001 Verilog Standard Compliant
//////////////////////////////////////////////////////////////////////////////////

module top_monitored_auto (
    input  wire        clk,
    input  wire        rst,
    input  wire        enable,
    input  wire        test_mode,
    input  wire [31:0] data_in,
    input  wire [31:0] key_in,
    output wire [31:0] data_out,
    output wire        corner_case_flag,
    output wire [15:0] ro1_freq,
    output wire [15:0] ro2_freq,
    output wire [15:0] freq_delta
);

    // Primary Datapath Instance
    top datapath_core (
        .clk(clk),
        .rst(rst),
        .enable(enable),
        .test_mode(test_mode),
        .data_in(data_in),
        .key_in(key_in),
        .data_out(data_out),
        .corner_case_flag(corner_case_flag)
    );

    // Sensor 1: Baseline Reference Sensor
    ring_oscillator ro_sensor_baseline (
        .enable(enable),
        .rare_net_in(1'b0),
        .ro_out(),
        .freq_count(ro1_freq)
    );

    // Sensor 2: Auto-Tapped Rare Net Sensor (Tapped Signal: {target_tap})
    ring_oscillator ro_sensor_tapped (
        .enable(enable),
        .rare_net_in({target_tap}),
        .ro_out(),
        .freq_count(ro2_freq)
    );

    // Differential Frequency Delta Calculation (|RO1 - RO2|)
    assign freq_delta = (ro1_freq >= ro2_freq) ? (ro1_freq - ro2_freq) : (ro2_freq - ro1_freq);

endmodule
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(verilog_code)

    print(f"[+] Auto-instrumented Verilog wrapper created: {output_path}")
    print(f"[+] Tapped Rare Signal Net(s): {sensor_taps_comment}")


def main():
    parser = argparse.ArgumentParser(
        description="Automated RO Sensor Instrumentation & Placement Tool"
    )
    parser.add_argument(
        "--verilog",
        type=str,
        default="lp_rtm.srcs/sources_1/new/top.v",
        help="Path to target Verilog design file (default: lp_rtm.srcs/sources_1/new/top.v)"
    )
    parser.add_argument(
        "--profile",
        type=str,
        default="reports/rare_nets_profile.json",
        help="Path to rare net JSON profile (default: reports/rare_nets_profile.json)"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="lp_rtm.srcs/sources_1/new/top_monitored_auto.v",
        help="Path to output auto-instrumented Verilog module (default: lp_rtm.srcs/sources_1/new/top_monitored_auto.v)"
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=2,
        help="Number of top rare nets to auto-instrument (default: 2)"
    )

    args = parser.parse_args()

    verilog_path = Path(args.verilog)
    profile_path = Path(args.profile)
    output_path = Path(args.output)

    print(f"[+] Reading rare net profile: {profile_path}")
    tapped_nets = parse_rare_profile(profile_path, args.top_n)

    print(f"[+] Instrumenting 5-stage Ring Oscillator sensors on: {tapped_nets}")
    generate_auto_monitored_verilog(verilog_path, tapped_nets, output_path)


if __name__ == "__main__":
    main()
